### ISSUE TITLE
Sidebar Issue in chrome 

### ISSUE THREAD

**Issue by vimalmistry** [codescandy/Dash-UI#16]
![Screenshot 2022-03-11 at 1 18 08 AM](https://user-images.githubusercontent.com/3993163/157743354-0ad972b4-e39b-4b21-98f7-7a06e40fe699.png)

The sidebar is overlapped. When I change max-width: 219 it's ok in chrome dev tools. This happens only in chrome :) 

Chrome: Version 99.0.4844.51 (Official Build) (x86_64)

**Comment by anitaparmar26** [comment]
Yes, it will because if you increase sidebar width so have to add margin from left in #page-content.
